export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN";

export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const PLAY_TRACK = "PLAY_TRACK";
export const PAUSE_TRACK = "PAUSE_TRACK";
export const HIDE_PLAYER = "HIDE_PLAYER";

export const GET_MUSICIAN_DETAILS_START = "GET_MUSICIAN_DETAILS_START";
export const GET_MUSICIAN_DETAILS_SUCCESS = "GET_MUSICIAN_DETAILS_SUCCESS";
export const GET_MUSICIAN_DETAILS_FAIL = "GET_MUSICIAN_DETAILS_FAIL";

export const GET_ALL_MUSICIANS = "GET_ALL_MUSICIANS";
export const GET_ALL_MUSICIANS_ERROR = "GET_ALL_MUSICIANS_ERROR";
export const GET_ALL_MUSICIANS_START = "GET_ALL_MUSICIANS_START";

export const UPDATE_MUSICIAN_PROFILE_START = "UPDATE_MUSICIAN_PROFILE_START";
export const UPDATE_MUSICIAN_PROFILE_SUCCESS =
  "UPDATE_MUSICIAN_PROFILE_SUCCESS";
export const UPDATE_MUSICIAN_PROFILE_FAIL = "UPDATE_MUSICIAN_PROFILE_FAIL";
export const DELETE_MUSICIAN_PROFILE_FAIL_ERROR =
  "DELETE_MUSICIAN_PROFILE_FAIL_ERROR";

export const GET_ALL_SONGS_START = "GET_ALL_SONGS_START";
export const GET_ALL_SONGS_SUCCESS = "GET_ALL_SONGS_SUCCESS";
export const GET_ALL_SONGS_FAIL = "GET_ALL_SONGS_FAIL";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_ISLOADING = "DELETE_SONG_ISLOADING";

export const UPDATE_USER_SONG_SUCCESS = "UPDATE_USER_SONG_SUCCESS";
export const UPDATE_USER_SONG_ERROR = "UPDATE_USER_SONG_ERROR";
export const UPDATE_USER_SONG_IS_LOADING = "UPDATE_USER_SONG_IS_LOADING";
export const DELETE_UPDATE_USER_SONG_ERROR = "DELETE_UPDATE_USER_SONG_ERROR";

export const GET_ALL_ALBUMS_START = "GET_ALL_ALBUMS_START";
export const GET_ALL_ALBUMS_SUCCESS = "GET_ALL_ALBUMS_SUCCESS";
export const GET_ALL_ALBUMS_FAIL = "GET_ALL_ALBUMS_FAIL";
export const DELETE_USER_ALBUM = "DELETE_USER_ALBUM";
export const DELETE_USER_ALBUM_ISLOADING = "DELETE_USER_ALBUM_ISLOADING";

export const SIGN_UP_ERRORS = "SIGN_UP_ERRORS";
export const IS_LOADING = "IS_LOADING";
export const DELETE_ERROR_MESSAGE = "DELETE_ERROR_MESSAGE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_IS_LOADING = "SIGN_UP_IS_LOADING";

export const SELECT_USER_ROLE = "SELECT_USER_ROLE";
export const SELECT_USER_ROLE_ERROR = "SELECT_USER_ROLE_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const SET_CURRENT_USER_ERROR = "SET_CURRENT_USER_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const DELETE_WARNING_MESSAGE = "DELETE_WARNING_MESSAGE";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";

export const UPLOAD_SONG_SUCCESS = "UPLOAD_SONG_SUCCESS";
export const UPLOAD_SONG_ERROR = "UPLOAD_SONG_ERROR";
export const UPLOAD_SONG_IS_LOADING = "UPLOAD_SONG_IS_LOADING";
export const DELETE_UPLOAD_SONG_ERROR = "DELETE_UPLOAD_SONG_ERROR";

export const UPLOAD_SONG_COVER_SUCCESS = "UPLOAD_SONG_COVER_SUCCESS";
export const UPLOAD_SONG_COVER_ERROR = "UPLOAD_SONG_COVER_ERROR";
export const UPLOAD_SONG_COVER_IS_LOADING = "UPLOAD_SONG_COVER_IS_LOADING";
export const DELETE_UPLOAD_SONG_COVER_ERROR = "DELETE_UPLOAD_SONG_COVER_ERROR";

export const GET_SINGLE_USER_SONG = "GET_SINGLE_USER_SONG";

export const UPLOAD_ALBUM_COVER_SUCCESS = "UPLOAD_ALBUM_COVER_SUCCESS";
export const UPLOAD_ALBUM_COVER_ERROR = "UPLOAD_ALBUM_COVER_ERROR";
export const UPLOAD_ALBUM_COVER_IS_LOADING = "UPLOAD_ALBUM_COVER_IS_LOADING";
export const DELETE_UPLOAD_ALBUM_COVER_ERROR =
  "DELETE_UPLOAD_ALBUM_COVER_ERROR";

export const UPLOAD_PROFILE_IMG_SUCCESS = "UPLOAD_PROFILE_IMG_SUCCESS";
export const UPLOAD_PROFILE_IMG_ERROR = "UPLOAD_PROFILE_IMG_ERROR";
export const UPLOAD_PROFILE_IMG_IS_LOADING = "UPLOAD_PROFILE_IMG_IS_LOADING";
export const DELETE_UPLOAD_PROFILE_IMG_ERROR =
  "DELETE_UPLOAD_PROFILE_IMG_ERROR";

export const POST_USER_SONG_SUCCESS = "POST_USER_SONG_SUCCESS";
export const POST_USER_SONG_ERROR = "POST_USER_SONG_ERROR";
export const POST_USER_SONG_IS_LOADING = "POST_USER_SONG_IS_LOADING";
export const DELETE_POST_USER_SONG_ERROR = "DELETE_POST_USER_SONG_ERROR";

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const FORGET_PASSWORD_IS_LOADING = "FORGET_PASSWORD_IS_LOADING";
export const DELETE_FORGET_PASSWORD_ERROR = "DELETE_FORGET_PASSWORD_ERROR";
export const VALIDATE_PASSWORD_TOKEN = "VALIDATE_PASSWORD_TOKEN";
export const VALIDATE_PASSWORD_TOKEN_SUCCESS =
  "VALIDATE_PASSWORD_TOKEN_SUCCESS";
export const VALIDATE_PASSWORD_TOKEN_ERROR = "VALIDATE_PASSWORD_TOKEN_ERROR";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_PASSWORD_IS_LOADING = "RESET_PASSWORD_IS_LOADING";
export const DELETE_RESET_PASSWORD_ERROR = "DELETE_RESET_PASSWORD_ERROR";

export const UPLOAD_USER_ALBUM_SUCCESS = "UPLOAD_USER_ALBUM_SUCCESS";
export const UPLOAD_USER_ALBUM_ERROR = "UPLOAD_USER_ALBUM_ERROR";
export const UPLOAD_USER_ALBUM_ISLOADING = "UPLOAD_USER_ALBUM_ISLOADING";
export const DELETE_UPLOAD_USER_ALBUM_ERROR = "DELETE_UPLOAD_USER_ALBUM_ERROR";

export const DELETE_SONG_IN_ALBUM_SUCCESS = "DELETE_SONG_IN_ALBUM_SUCCESS";
export const DELETE_SONG_IN_ALBUM_ERROR = "DELETE_SONG_IN_ALBUM_ERROR";
export const DELETE_SONG_IN_ALBUM_ISLOADING = "DELETE_SONG_IN_ALBUM_ISLOADING";

export const UPDATE_USER_ALBUM_SONG_SUCCESS = "UPDATE_USER_ALBUM_SONG_SUCCESS";
export const UPDATE_USER_ALBUM_SONG_ERROR = "UPDATE_USER_ALBUM_SONG_ERROR";
export const UPDATE_USER_ALBUM_SONG_ISLOADING =
  "UPDATE_USER_ALBUM_SONG_ISLOADING";
export const DELETE_UPDATE_USER_ALBUM_SONG_ERROR =
  "DELETE_UPDATE_USER_ALBUM_SONG_ERROR";

export const UPDATE_ALBUM_TITLE_AND_COVER_SUCCESS =
  "UPDATE_ALBUM_TITLE_AND_COVER_SUCCESS";
export const UPDATE_ALBUM_TITLE_AND_COVER_ERROR =
  "UPDATE_ALBUM_TITLE_AND_COVER_ERROR";
export const UPDATE_ALBUM_TITLE_AND_COVER_ISLOADING =
  "UPDATE_ALBUM_TITLE_AND_COVER_ISLOADING";
export const DELETE_UPDATE_ALBUM_TITLE_AND_COVER_ERROR =
  "DELETE_UPDATE_ALBUM_TITLE_AND_COVER_ERROR";

export const UPLOAD_UPDATED_SONG_IN_ALBUM_SUCCESS =
  "UPLOAD_UPDATED_SONG_IN_ALBUM_SUCCESS";
export const UPLOAD_UPDATED_SONG_IN_ALBUM_ERROR =
  "UPLOAD_UPDATED_SONG_IN_ALBUM_ERROR";
export const UPLOAD_UPDATED_SONG_IN_ALBUM_ISLOADING =
  "UPLOAD_UPDATED_SONG_IN_ALBUM_ISLOADING";
export const DELETE_UPLOAD_UPDATED_SONG_IN_ALBUM_ERROR =
  "DELETE_UPLOAD_UPDATED_SONG_IN_ALBUM_ERROR";

export const UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_SUCCESS =
  "UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_SUCCESS";
export const UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ERROR =
  "UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ERROR";
export const UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ISLOADING =
  "UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ISLOADING";
export const DELETE_UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ERROR =
  "DELETE_UPLOAD_UPDATED_SONG_COVER_IN_ALBUM_ERROR";
